name: publish

on:
  push:
    branches: [ master, main ]
    
env:
  DOTNET_VERSION: 5.x # The .NET SDK version to use
 
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore src/FizzBuzzPackage
    - name: Build
      run: dotnet build src/FizzBuzzPackage --configuration Release --no-restore
    - name: Test
      run: dotnet test src/FizzBuzzPackage.Tests --no-restore --verbosity normal
    - name: Pack the project
      run: dotnet pack src/FizzBuzzPackage --output .
    - name: Publish the package to GitHub Packages
      run: dotnet nuget push FizzBuzzPackage.*.nupkg -s https://nuget.pkg.github.com/taboo09/index.json -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
